//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.BlogService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BlogService.IBlogService")]
    public interface IBlogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/HelloBloggers", ReplyAction="http://tempuri.org/IBlogService/HelloBloggersResponse")]
        string HelloBloggers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/HelloBloggers", ReplyAction="http://tempuri.org/IBlogService/HelloBloggersResponse")]
        System.Threading.Tasks.Task<string> HelloBloggersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/CreateAUser", ReplyAction="http://tempuri.org/IBlogService/CreateAUserResponse")]
        void CreateAUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/CreateAUser", ReplyAction="http://tempuri.org/IBlogService/CreateAUserResponse")]
        System.Threading.Tasks.Task CreateAUserAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlogServiceChannel : ConsoleApplication1.BlogService.IBlogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlogServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.BlogService.IBlogService>, ConsoleApplication1.BlogService.IBlogService {
        
        public BlogServiceClient() {
        }
        
        public BlogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloBloggers() {
            return base.Channel.HelloBloggers();
        }
        
        public System.Threading.Tasks.Task<string> HelloBloggersAsync() {
            return base.Channel.HelloBloggersAsync();
        }
        
        public void CreateAUser(string username, string password) {
            base.Channel.CreateAUser(username, password);
        }
        
        public System.Threading.Tasks.Task CreateAUserAsync(string username, string password) {
            return base.Channel.CreateAUserAsync(username, password);
        }
    }
}
