//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adminwebsite.service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="service.IBlogService")]
    public interface IBlogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/HelloBloggers", ReplyAction="http://tempuri.org/IBlogService/HelloBloggersResponse")]
        string HelloBloggers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/HelloBloggers", ReplyAction="http://tempuri.org/IBlogService/HelloBloggersResponse")]
        System.Threading.Tasks.Task<string> HelloBloggersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/EchoUserInput", ReplyAction="http://tempuri.org/IBlogService/EchoUserInputResponse")]
        string EchoUserInput(string echoInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlogService/EchoUserInput", ReplyAction="http://tempuri.org/IBlogService/EchoUserInputResponse")]
        System.Threading.Tasks.Task<string> EchoUserInputAsync(string echoInput);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlogServiceChannel : Adminwebsite.service.IBlogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlogServiceClient : System.ServiceModel.ClientBase<Adminwebsite.service.IBlogService>, Adminwebsite.service.IBlogService {
        
        public BlogServiceClient() {
        }
        
        public BlogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloBloggers() {
            return base.Channel.HelloBloggers();
        }
        
        public System.Threading.Tasks.Task<string> HelloBloggersAsync() {
            return base.Channel.HelloBloggersAsync();
        }
        
        public string EchoUserInput(string echoInput) {
            return base.Channel.EchoUserInput(echoInput);
        }
        
        public System.Threading.Tasks.Task<string> EchoUserInputAsync(string echoInput) {
            return base.Channel.EchoUserInputAsync(echoInput);
        }
    }
}
