//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace CustomerSite.CustomerWebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IBlogService", Namespace="http://tempuri.org/")]
    public partial class BlogService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloBloggersOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostNewEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReturnEntriesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BlogService() {
            this.Url = global::CustomerSite.Properties.Settings.Default.CustomerSite_CustomerWebservice_BlogService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloBloggersCompletedEventHandler HelloBloggersCompleted;
        
        /// <remarks/>
        public event PostNewEntryCompletedEventHandler PostNewEntryCompleted;
        
        /// <remarks/>
        public event ReturnEntriesCompletedEventHandler ReturnEntriesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBlogService/HelloBloggers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HelloBloggers() {
            object[] results = this.Invoke("HelloBloggers", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloBloggersAsync() {
            this.HelloBloggersAsync(null);
        }
        
        /// <remarks/>
        public void HelloBloggersAsync(object userState) {
            if ((this.HelloBloggersOperationCompleted == null)) {
                this.HelloBloggersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloBloggersOperationCompleted);
            }
            this.InvokeAsync("HelloBloggers", new object[0], this.HelloBloggersOperationCompleted, userState);
        }
        
        private void OnHelloBloggersOperationCompleted(object arg) {
            if ((this.HelloBloggersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloBloggersCompleted(this, new HelloBloggersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBlogService/PostNewEntry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PostNewEntry([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string newBlogEntry) {
            this.Invoke("PostNewEntry", new object[] {
                        newBlogEntry});
        }
        
        /// <remarks/>
        public void PostNewEntryAsync(string newBlogEntry) {
            this.PostNewEntryAsync(newBlogEntry, null);
        }
        
        /// <remarks/>
        public void PostNewEntryAsync(string newBlogEntry, object userState) {
            if ((this.PostNewEntryOperationCompleted == null)) {
                this.PostNewEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostNewEntryOperationCompleted);
            }
            this.InvokeAsync("PostNewEntry", new object[] {
                        newBlogEntry}, this.PostNewEntryOperationCompleted, userState);
        }
        
        private void OnPostNewEntryOperationCompleted(object arg) {
            if ((this.PostNewEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostNewEntryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IBlogService/ReturnEntries", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReturnEntries() {
            object[] results = this.Invoke("ReturnEntries", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnEntriesAsync() {
            this.ReturnEntriesAsync(null);
        }
        
        /// <remarks/>
        public void ReturnEntriesAsync(object userState) {
            if ((this.ReturnEntriesOperationCompleted == null)) {
                this.ReturnEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnEntriesOperationCompleted);
            }
            this.InvokeAsync("ReturnEntries", new object[0], this.ReturnEntriesOperationCompleted, userState);
        }
        
        private void OnReturnEntriesOperationCompleted(object arg) {
            if ((this.ReturnEntriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnEntriesCompleted(this, new ReturnEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloBloggersCompletedEventHandler(object sender, HelloBloggersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloBloggersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloBloggersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void PostNewEntryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReturnEntriesCompletedEventHandler(object sender, ReturnEntriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnEntriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnEntriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591